= Universalis - Missionen
include::_attributes.adoc[]
:description: Missionen für Universalis.

== Spielfeldgröße

Die im folgenden beschriebenen Missionen beziehen sich immer auf eine Spielfeldgröße von 36" * 36".

[.text-center]
image:Grafiken/Abbildungen/spielfeld.svg[Spielfeld,width=300]

Die Aufstellungszone ist jeweils der grün schraffierte Bereich.

Sofern eine Mission weitere Zonen benötigt werden diese ebenfalls schraffiert, aber in anderen Farben dargestellt.

== Bergung

Das Spiel ist gewonnen, sobald sich am Ende einer Initiativephase mindestens X - 1 `[Gegenstände]` in der eigenen Aufstellungszone befinden.

image:Grafiken/Missionen/Bergung/01.svg[Mission 3,width=300]

== Einnehmen

#TODO

== Eliminierung

Das Spiel ist gewonnen, sobald alle Modelle des Gegners eliminiert oder vom Spielfeld entfernt worden sind.

image:Grafiken/Missionen/Eliminierung/01.svg[Mission 1,width=300]
image:Grafiken/Missionen/Eliminierung/02.svg[Mission 2,width=300]
image:Grafiken/Missionen/Eliminierung/03.svg[Mission 2,width=300]

== Extraktion

Das Spiel ist gewonnen, sobald am Ende einer Initiativephase mindestens die Hälfte aller eigenen Modelle (aufgerundet) die Extraktionszone (in rot) erreicht haben.

image:Grafiken/Missionen/Extraktion/01.svg[Mission 4,width=300]
image:Grafiken/Missionen/Extraktion/02.svg[Mission 4,width=300]
image:Grafiken/Missionen/Extraktion/03.svg[Mission 4,width=300]

== Transport

Das Spiel ist gewonnen, sobald sich am Ende einer Initiativephase mindestens X - 1 `[Gegenstände]` in den Zielzonen (in rot) befinden.

image:Grafiken/Missionen/Transport/01.svg[Mission 5,width=300]
image:Grafiken/Missionen/Transport/02.svg[Mission 6,width=300]
image:Grafiken/Missionen/Transport/03.svg[Mission 5,width=300]