= Universalis - Regelbuch
Markus Lobedann <markus.lobedann@gmail.com>
:doctype: book
:description: Ein universeller Tabletop Skirmisher.
:revnumber: 0.5.0
:data-uri: {docdir}
:toc: left
:toclevels: 2
:toc-title: Inhaltsverzeichnis
:preface-title: Vorwort
:sectnums:
:sectnumlevels: 2
:section-refsig: 
ifdef::backend-html5[]
:stylesheet: style/html-theme.css
endif::[]
ifdef::backend-pdf[]
:title-logo-image: image::../Grafiken/logo.svg[logo,width=400]
:pdf-fontsdir: ../Fonts
:pdf-style: style/pdf-theme.yml
:media: prepress
endif::[]
:xrefstyle: full

_Universalis_ versucht ein universeller Tabletop Skirmisher für 28mm zu
sein der kleine Spiele mit wenigen Modellen in den Vordergrund stellt.
Er ist nicht auf ein konkretes Szenario zugeschnitten und kann in jedem
beliebigen Universum spielen.

_Universalis_ versucht in keinster Weise ein Turniersystem zu sein oder
perfekt ausbalancierte Spiele zu bieten. Die ((Spieler)) sollen eine tolle
Geschichte erleben mit all ihren Hochs und Tiefs, egal wie sie konkret
ausgeht.

Eine der Ideen hinter _Universalis_ ist es beliebige ((Modelle)) einzusetzen
um tolle Einheiten aufzustellen, ohne in irgendeiner Art und Weise
eingeschräkt zu sein. WYSIWYG ist zwar eine tolle Sache und empfohlen,
aber in keinster Weise vorgeschrieben. Niemand darf erwarten, dass man
seine älteren Modelle in die viel Arbeit geflossen ist nur wegen eines
neuen Spiels umbaut oder ersetzt.

Refer to <<Und noch ein Unterpunkt>>

Modelle sollten halbwegs realistisch ausgerüstet werden und nicht mit
beliebig vielen Nahkampf- und Fernkampfwaffen und
Ausrüstungsgegebständen überhäuft werden um auf jede Situation eine
Antwort zu haben.

Am Ende sollte jederzeit der gesunde Menschenverstand mitspielen und der
Spaß am kontinuierlichen Spiel im Vordergrund stehen.

Also:

. Nehmt eure schönsten Modelle
. Stellt coole Teams zusammen
. Erzählt eine tolle Geschichte
. Habt Spaß!

== Was braucht man

* Ein ((Tisch)) mit einer Fläche von mindestens 90cm * 90cm.

image:Grafiken/Abbildungen/spielfeld.svg[spielfeld,width=400,align=center]

* Ausreichend link:#geländeteile[Geländeteile] um die Fläche gut zu
füllen.
* Für jeden Spieler ein Maßband oder einen Maßstab mit Markierungen in
Zentimetern.

image:Grafiken/Abbildungen/maßband.svg[Maßband,200,50]
aslökdjaölsdj alskdj öalskdjöa sjdöosdjf osaijf osijdfsjd üfiojsdüfioj sdüfoijsüadiofj üsiodjfüiosjd fijsdö foijsdifoj soidjfiosj dfüiojs düfoij sadüfioj üsiojf üsaoijfüiosajd füoijsdfüij saüfdioj süoidfjüsidjf üisjdf üjsdüfijs düfijüsdfj üiaosjdfüij f aksldjsdlk asöldkjaö ldkjsödfj söodkjöslkdjöslk jföksajf öksajdfölkjsa ölfkjsaöldjask jfökljas ödkjfksj dfölkjasödl kfjöaslkdjf ölksajdfölkjasdöfljasöldkfjölsakj dfölsakjdfökj asödfkjsaö lkdfjöskajdf öjasfökjasdföjsökdjf ösjf kjöfkj södfjösakjf ölkjsödlfjaöslkjdflkasj ödfj
image:Grafiken/Abbildungen/maßstab.svg[Maßstab,200,50]

* Für jeden ((Spieler)) mindestens 2 link:#modelle[Modelle] und dazugehörige

=== Nächster Unterpunkt

asöldo jadslkfj saädkfjäsldf
+asd f+üasldf üpdkf ösd

as ljasö dlkjasölkj sdölkfjs df

==== Und noch ein Unterpunkt

a-dj aslkjd öaslkjd ölaksjd ölaksjd ölkasd kasjd lkjahsd lkasbhl kjabsdljba sldkjbasldjbaslk

ifdef::backend-pdf[]
[index]
== Stichwortverzeichnis
endif::[]